include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/app/**      # UI 层本阶段不交付，为避免分析噪声先行排除
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - always_declare_return_types
